language: cpp

install:
- if [[ "$PLATFORM" == "android" ]]; then wget -q http://dl.google.com/android/ndk/android-ndk-r10d-linux-x86_64.bin -O /tmp/android-ndk-r10d-linux-x86_64.bin && chmod +x /tmp/android-ndk-r10d-linux-x86_64.bin && /tmp/android-ndk-r10d-linux-x86_64.bin > /dev/null && rm /tmp/android-ndk-r10d-linux-x86_64.bin; fi

script:
- git clone --branch release-1.8.0 --depth 1 https://github.com/google/googletest.git
- if [[ "$PLATFORM" == "android" ]]; then git clone --depth 1 https://github.com/taka-no-me/android-cmake.git; fi
- if [[ "$PLATFORM" == "linux" ]] || [[ "$PLATFORM" == "macos" ]]; then cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=1 .; fi
- if [[ "$PLATFORM" == "android" ]]; then cmake -DANDROID_NDK=./android-ndk-r10d -DCMAKE_TOOLCHAIN_FILE=./android-cmake/android.toolchain.cmake -DANDROID_ABI="armeabi-v7a with NEON" -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=1 .; fi
- cmake --build . --config Release

after_success:
- if [[ "$PLATFORM" == "linux" ]] || [[ "$PLATFORM" == "macos" ]]; then ./hwtrycatch_tests; fi

matrix:
    include:
        - os: linux
          dist: trusty
          sudo: false
          env: PLATFORM=linux
        - os: linux
          dist: trusty
          sudo: false
          env: PLATFORM=android
        - os: osx
          osx_image: xcode8
          env: PLATFORM=macos
