language: cpp

script:
  - git clone --branch release-1.10.0 --depth 1 https://github.com/google/googletest.git
  - if [[ "$TRAVIS_OS_NAME" == "linux" || "$TRAVIS_OS_NAME" == "osx" ]]; then cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=1 -G "Unix Makefiles" .; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then cmake -DCMAKE_VERBOSE_MAKEFILE=1 -G "Visual Studio 15 2017 Win64" .; fi
  - cmake --build . --config Release
  - if [[ "$TRAVIS_OS_NAME" == "linux" || "$TRAVIS_OS_NAME" == "osx" ]]; then ./hwtrycatch_tests; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then ./Release/hwtrycatch_tests.exe; fi

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
    - os: linux
      dist: xenial
      sudo: false
    - os: linux
      dist: bionic
      sudo: false
    - os: osx
      osx_image: xcode8
    - os: osx
      osx_image: xcode8.3
    - os: osx
      osx_image: xcode9
    - os: osx
      osx_image: xcode9.4
    - os: osx
      osx_image: xcode10
    - os: osx
      osx_image: xcode10.3
    - os: osx
      osx_image: xcode11
    - os: osx
      osx_image: xcode11.6
    - os: osx
      osx_image: xcode12
    - os: windows
