language: cpp

script:
- git clone --branch release-1.8.1 --depth 1 https://github.com/google/googletest.git
- cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=1 .
- cmake --build . --config Release

after_success:
- ./hwtrycatch_tests

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
    - os: linux
      dist: xenial
      sudo: false
    - os: osx
      osx_image: xcode8
    - os: osx
      osx_image: xcode8.3
    - os: osx
      osx_image: xcode9
    - os: osx
      osx_image: xcode9.4
    - os: osx
      osx_image: xcode10
    - os: osx
      osx_image: xcode10.1
