environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CMAKE_GENERATOR: Visual Studio 14 2015
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_GENERATOR: Visual Studio 15 2017
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CMAKE_GENERATOR: Visual Studio 16 2019

build_script:
  - cmd: |
      git clone --branch release-1.10.0 --depth 1 https://github.com/google/googletest.git
      cmake -G "%CMAKE_GENERATOR%" -A x64 .
      cmake --build . --config Release

test_script:
  - cmd: |
      .\Release\hwtrycatch_tests.exe
