version: 0.0.{build}
build_script:
- cmd: >-
    git clone --branch release-1.8.0 --depth 1 https://github.com/google/googletest.git

    cmake .

    cmake --build . --config Release
test_script:
- cmd: .\Release\hwtrycatch_tests.exe
